escambox/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #django admin
    path('admin/', admin.site.urls),

    #user management
    path("accounts/", include("allauth.urls")),

    #local
    path("", include("pages.urls", namespace = "pages")),
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name='home'),
    path("accounts/", views.AccountsPageView.as_view(), name='accounts'),
    path("accounts/<int:pk>/", views.AccountDetailView.as_view(), name='accountdetail'),
    path("products/", views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='productdetail'),
    path('products/add/', views.ProductCreateView.as_view(), name='productcreate'),
    path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='productupdate'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='productdelete'),
    path('products/sell/<int:pk>/', views.ProductSellView.as_view(), name='productsell'),
    path("trades/", views.TradeListView.as_view(), name='trades'),
    path("reports/", views.ReportListView.as_view(), name='reports'),
    path("reports/add?pk=<int:pk>", views.ReportCreateView.as_view(), name='reportcreate'),
    path("reports/<int:pk>/", views.ReportDetailView.as_view(), name='reportdetail'),
    path("reports/<int:pk>/", views.ReportDetailView.as_view(), name='reportaccept'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/products/create.html
{% extends 'base.html' %}

{% block title %}Create product{% endblock %}

{% block content %}
    <h1>Create a product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <input type="submit" class="form-control btn btn-success" value="Create product"/>
    </form>
{% endblock %}

templates/products/delete.html
{% extends 'base.html' %}

{% block title %}Delete product{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="post-form contact-form">
        {% csrf_token %}
        <h1>Do you want to delete the product "{{ object.title }}?"</h1>
        <input type='submit' value="Yes" class="btn btn-success">
        <a href="{% url 'pages:products' %}" class="btn btn-danger"> No </a>
    </form>
{% endblock %}

templates/products/index.html
{% extends 'base.html' %}

{% block title %}Products{% endblock %}

{% block content %}
    <h1>Products</h1>
    <p><b>In this page you can find all the available products and get in touch with the sellers.</b></p>
    <div class = "row my-4">
        {% if request.user.is_authenticated %}
            <div class="col-3">
                <a href="{% url 'pages:productcreate' %}" class="btn btn-info btn-sm">Create new product ➕</a>
            </div>
        {% endif %}
        
            <form action="." method="GET" class="form-inline col-9">
                    <input type="text" id="search" name="search" class="form-control"  placeholder="Search for a product">
                    <input type="submit" class="btn btn-primary btn-sm" style="margin-left:5px;" value="Search 🔎">
                {% if request.user.is_authenticated %}
                        <div class="btn-group ml-5" role="group">
                            {% if request.GET.favorites == "true" %}
                                <button name="favorites" class="btn btn-warning btn-sm active" value="false">Favorites ❤️</button>
                            {% else %}
                                <button name="favorites" class="btn btn-warning btn-sm" value="true">Favorites ❤️</button>
                            {% endif %}

                            {% if request.GET.own_products == "true" %}
                            <button name="own_products" class="btn btn-primary btn-sm active" value="false">My own products 😀</button>
                            {% else %}
                                <button name="own_products" class="btn btn-primary btn-sm" value="true">My own products 😀</button>
                            {% endif %}
                            
                        </div>
                {% endif %}
            </form>
        </div>
    </div>
    <div class="card-columns">
        {% for product in products %}
                <div class="card shadow-sm">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top" style="object-fit: cover; aspect-ratio: 1/1;" />
                    {% else %}
                        <img src="/static/placeholder.png" class="card-img-top" style="object-fit: cover; aspect-ratio: 1/1;"/>
                    {% endif %}
                    <h5 class="card-header">{{ product.title }}</h5>
                    <div class="card-body">
                        {% if product.description == "" %}
                        <p class="card-text text-muted font-italic">No description added</p>
                        {% else %}
                            <p class="card-text">{{ product.description }}</p>
                        {% endif %}
                        <p class="font-weight-bold">R$ {{ product.price }}</p>
                        <a href="{% url 'pages:productdetail' pk=product.id %}" class="stretched-link"></a>
                    </div>
                </div>
        {% endfor %}
        </div>

    {% if page_obj is not None %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

templates/products/product.html
{% extends 'base.html' %}

{% block title %}ESCAMBOX | {{ object.title }}{% endblock %}

{% block content %}
  <div class="card-group">
    <div class="card shadow-sm">
      {% if product.image %}
          <img src="{{ product.image.url }}" class="card-img-top" style="object-fit: cover; aspect-ratio: 1/1;" />
      {% else %}
          <img src="/static/placeholder.png" class="card-img-top" style="object-fit: cover; aspect-ratio: 1/1;"/>
      {% endif %}
    </div>

    <div class="card shadow-sm">
      <h5 class="card-header">{{ product.title }}</h5>
      <div class="card-body">
        {% if product.description == "" %}
        <p class="card-text text-muted font-italic">No description added</p>
        {% else %}
            <p class="card-text">{{ product.description }}</p>
        {% endif %}
        <a href="{% url 'pages:productdetail' pk=product.id %}"></a>

        {% if request.user.is_authenticated %}
          <div class="bg-light">Please, send your offer to: {{ product.original_owner.email }}</div>
        {% else %}
          <div class="bg-light">Please, log in to see the owner of this product.</div>
        {% endif %}
      </div>
      <div class="card-footer">
        <span class="btn-group">
        {% if request.user.is_authenticated %}
          <a class="btn-sm btn-primary" href="https://twitter.com/intent/tweet?text=Look%20{{object.title|urlencode}}%20for%20only%20R$%20{{object.price|urlencode}}%20on%20Escambox!%20http%3A//127.0.0.1%3A8000/products/{{object.id}}/" >Share on Twitter ✉️</a>
          {% if owner == request.user %}
            {% if object.sold == False %}
              <a href="{% url 'pages:productsell' pk=product.id %}" class="btn-sm btn-info ml-1" >Sold 🤑</a>
            {% endif %}
            <a href="{% url 'pages:productupdate' pk=product.id %}" class="btn-sm btn-success ml-1">Update ♻️</a>
            <a href="{% url 'pages:productdelete' pk=product.id %}" class="btn-sm btn-danger ml-1">Delete 🗑️</a>
          {% else %}
            <a href="{% url 'pages:reportcreate' pk=product.id %}" class="btn btn-danger ml-1">Report product ❗</a>
            <form method="post" id="formTwo">
              {% csrf_token %}
              <input type="hidden" name="form_type" value="formTwo">
              {% if is_already_liked %}
                <button class="btn btn-danger ml-1" name="like" value="dislike">Dislike 👎</button>
              {% else %}
                <button class="btn btn-success ml-1" name="like" value="like">Like 👍</button>
              {% endif %}
            </form>
          {% endif %}
        {% endif %}
        </span>
        <span class="font-weight-bold float-right h4">R$ {{ product.price }}</span>
      </div>
    </div>
  </div>
{% endblock %}

templates/products/sell.html
{% extends 'base.html' %}

{% block title %}Sell product{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="post-form contact-form">
        {% csrf_token %}
        <h1>Sell product "{{ object.title }}?"</h1>
        <div class="form-group">
            <label>Email address of the buyer</label>
            <input type="email" class="form-control" name="buyer_email" aria-describedby="emailHelp" placeholder="Enter email">
        </div>

        <div class="form-group">
        <label>Observation (optional)</label>
        <input type="text" class="form-control-file" name="observation">
        </div>

        <input type='submit' value="Sell" class="btn btn-success">
        <a href="{% url 'pages:products' %}" class="btn btn-danger"> Go back </a>
    </form>
{% endblock %}

templates/products/update.html
{% extends 'base.html' %}

{% block title %}ESCAMBOX | {{ object.title }}{% endblock %}

{% block content %}
    <h1>Update {{ object.title }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <input type="submit" class="form-control btn btn-success" value="Update product"/>
    </form>
{% endblock %}