escambox/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #django admin
    path('admin/', admin.site.urls),

    #user management
    path("accounts/", include("allauth.urls")),

    #local
    path("", include("pages.urls", namespace = "pages")),
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name='home'),
    path("accounts/", views.AccountsPageView.as_view(), name='accounts'),
    path("accounts/<int:pk>/", views.AccountDetailView.as_view(), name='accountdetail'),
    path("products/", views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='productdetail'),
    path('products/add/', views.ProductCreateView.as_view(), name='productcreate'),
    path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='productupdate'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='productdelete'),
    path('products/sell/<int:pk>/', views.ProductSellView.as_view(), name='productsell'),
    path("trades/", views.TradeListView.as_view(), name='trades'),
    path("reports/", views.ReportListView.as_view(), name='reports'),
    path("reports/add?pk=<int:pk>", views.ReportCreateView.as_view(), name='reportcreate'),
    path("reports/<int:pk>/", views.ReportDetailView.as_view(), name='reportdetail'),
    path("reports/<int:pk>/", views.ReportDetailView.as_view(), name='reportaccept'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/reports/create.html
{% extends 'base.html' %}

{% block title %}Report product{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" class="post-form contact-form">
        {% csrf_token %}
        <h1>Why do you want to report the product: "{{ product.title }}?"</h1>

        {{ form.as_p }}
        <input type="hidden" name="product_id" value="{{ product.id }}">
        <input type='submit' value="Report" class="btn btn-success">
        <a href="{% url 'pages:products' %}" class="btn btn-danger">Cancel</a>
    </form>
{% endblock %}

templates/reports/index.html
{% extends 'base.html' %}

{% block title %}Reports{% endblock %}

{% block content %}
    <h1>Product reports</h1>
    <p><b>This page contains all the reports registered in the platform.</b></p>
    <ul class="list-group">
        {% for report in reports %}
            <div class="card shadow-sm">
                <h5 class="card-header">{{ report.product.title }}</h5>
                <div class="card-body">
                    <p class="card-text">{{ report.description }}</p>
                    <a href="{% url 'pages:reportdetail' pk=report.id %}" class="stretched-link"></a>
                </div>
            </div>
        {% endfor %}
    </ul>

    {% if page_obj is not None %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
{% endblock %}

templates/reports/report.html
{% extends 'base.html' %}

{% block title %}ESCAMBOX | Report {{ product.title }}{% endblock %}

{% block content %}
    <h1>Report for {{ product.title }}:</h1>
    <div class="form-group row">
      <label for="description" class="font-weight-bold col-sm-2 col-form-label">This product was reported by</label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext" id="description" value="{{ report.reporter }}">
      </div>
    </div>
    <div class="form-group row">
      <label for="description" class="font-weight-bold col-sm-2 col-form-label">Reason</label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext" id="description" value="{{ report.description }}">
      </div>
    </div>
    <div class="form-group row">
      <label for="created_at" class="font-weight-bold col-sm-2 col-form-label">Reported at</label>
      <div class="col-sm-10">
        <input type="text" readonly class="form-control-plaintext" id="created_at" value="{{ report.created_at }}">
      </div>
    </div>
    <br>
    <br>
    <h2>The announcement:</h2>
    <br>
    <div class="form-group border bg-light">
      <form>
        {% if product.image %}
          <div class="form-group row">
            <img src="{{ product.image.url }}" class="col-4 mr-4 rounded float-left img-fluid"/>
          </div>
        {% endif %}
        <h1>{{ product.title|upper }}</h1>
        <div class="form-group row">
          <label for="description" class="font-weight-bold col-sm-2 col-form-label">Description</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="description" value="{{ product.description }}">
          </div>
        </div>
        <div class="form-group row">
          <label for="price" class="font-weight-bold col-sm-2 col-form-label">Price</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="price" value="R$ {{ product.price }}">
          </div>
        </div>
        <div class="form-group row">
          <label for="created_at" class="font-weight-bold col-sm-2 col-form-label">Created at</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="created_at" value="{{ product.created_at }}">
          </div>
        </div>
        <div class="form-group row">
          <label for="owner" class="font-weight-bold col-sm-2 col-form-label">Owned by</label>
          <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="owner" value="{{ owner }}">
          </div>
        </div>
      </form>
    </div>

    {% if request.user.is_authenticated and request.user.is_staff %}
      <form method="post" id="report">
        {% csrf_token %}
        <input type="hidden" name="form_type" value="formTwo">
        <button class="btn btn-danger ml-1" name="accept" value="reject">Accept report (will delete the product)</button>
        <button class="btn btn-success ml-1" name="accept" value="cancel">Cancel</button>
      </form>
    {% endif %}
    <br><br>
{% endblock %}