escambox/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    #django admin
    path('admin/', admin.site.urls),

    #user management
    path("accounts/", include("allauth.urls")),

    #local
    path("", include("pages.urls", namespace = "pages")),
]

pages/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name='home'),
    path("accounts/", views.AccountsPageView.as_view(), name='accounts'),
    path("accounts/<int:pk>/", views.AccountDetailView.as_view(), name='accountdetail'),
    path("products/", views.ProductListView.as_view(), name='products'),
    path('products/<int:pk>/', views.ProductDetailView.as_view(), name='productdetail'),
    path('products/add/', views.ProductCreateView.as_view(), name='productcreate'),
    path('products/update/<int:pk>/', views.ProductUpdateView.as_view(), name='productupdate'),
    path('products/delete/<int:pk>/', views.ProductDeleteView.as_view(), name='productdelete'),
    path('products/sell/<int:pk>/', views.ProductSellView.as_view(), name='productsell'),
    path("trades/", views.TradeListView.as_view(), name='trades'),
    path("reports/", views.ReportListView.as_view(), name='reports'),
    path("reports/add?pk=<int:pk>", views.ReportCreateView.as_view(), name='reportcreate'),
    path("reports/<int:pk>/", views.ReportDetailView.as_view(), name='reportdetail'),
    path("reports/<int:pk>/", views.ReportDetailView.as_view(), name='reportaccept'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

</head>
<body>
<header>

    <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">

        <a class="navbar-brand" href="{% url 'pages:home' %}"><b>⇄ ESCAMBOX</b></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav d-flex justify-content-end mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pages:products' %}">Products</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:trades' %}">My trades</a>
                    </li>

                    {% if request.user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:accounts' %}">Accounts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:reports' %}">Reports</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:accountdetail' pk=request.user.id %}">My account</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'pages:reports' %}">My reports</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>

        <div class="container justify-content-end">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link">Hello, {{request.user.username}}!</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Sign-up</a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>
</header>

<main class="container">
    {% block content %}
    {% endblock %}
</main>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}ESCAMBOX{% endblock %}

{% block content %}
    <p><b>ESCAMBOX is an online platform for trading goods.</b></p>
    <p><b>Here all the users can post their goods and get in touch with sellers!</b></p>
    <p>
        <a href="{% url 'pages:products' %}" class="btn btn-primary">Products</a>
    </p>
{% endblock %}